---
title: "Housing Investment Reccommendation for SREIT"
author: "Tajudeen Abdulazeez"
date: "May 15, 2019"
output: html_document
---

## Load Packages
```{r load-packages}
library(ggplot2)
library(maps)  # making making 
library(mapproj)  # projections for map making
library(spgwr)  # spatially-weighted regression
library(rpart)  # tree-structured modeling
library(randomForest)  # random forests
library(rpart.plot)  # plot tree-structured model information
library(lattice)  # statistical graphics
library(cvTools)  # cross-validation tools including rmspe 


#library(tidyverse)
library(ggplot2)
library(ggmap)
library(readxl)
library(zipcode)


library(plotly)
packageVersion('plotly')



```

## Read Data
```{r load-data}

df <- read.csv('single_family_prep.csv')
head(df,3)

```

## Dataframe summary
```{r}
summary(df)
```


## Data type conversion
```{r data-type-conversion}

df$RegionID <- as.factor(df$RegionID)
df$RegionName <- as.factor(df$RegionName)
df$SizeRank <- as.ordered(df$SizeRank)
df$Date <- as.Date(df$Date)

summary(df)
```


## create a new column , Year and Month
```{r}
temp <- df

temp[, "year"] <- format(temp[,"Date"], "%Y")
temp[, "month"] <- format(temp[,"Date"], "%m")

head(temp)

```

```{r}
df <- temp
colnames(df)

```


```{r}
data("zipcode")

dfzip <- data.frame(zipcode)

head(dfzip)

```

merge the two dataframe

```{r}
df_merge  <- merge(df, dfzip, by.x='RegionName', by.y='zip')

head(df_merge)

```

```{r}
write.csv(df_merge,'single_family_with_geo.csv')
```


create a dataframe with full state name and state abbreviation

```{r}
dfstate <- data.frame(state.abb,state.name)
colnames(dfstate) <- c('state','statename')
head(dfstate)

```

Merge the state dataframe
```{r}
df_clean <- merge(df_merge, dfstate, by.x ='State', by.y='state')

head(df_clean)

```


Write the clean data to csv
```{r}
write.csv(df_clean,'single_family_with_geo.csv')
```


Convert state to lower case . ggmap works with lowercase

```{r}

df_clean$statename <- tolower(df_clean$statename)
df_clean$city <- tolower(df_clean$city)
head(df_clean)

```


Map

```{r}
us <- map_data('state')
head(us)
```





